name: Run Vinted Bot every 10 minutes

on:
  schedule:
    - cron: '*/10 * * * *'  # toutes les 10 minutes
  workflow_dispatch:

jobs:
  run_bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install requests
      - name: Run bot script
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: python vinted_bot.py
